{
    "openapi": "3.0.0",
    "info": {
        "title": "meufrete.com",
        "description": "This is an API Rest",
        "version": "1.0.0"
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "create a user",
                "description": "Create a new user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/CreateUser"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Driver already exists"
                    }
                }
            }
        },
        "/loads": {
            "post": {
                "tags": [
                    "Loads"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "create a load",
                "description": "Create a new load",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Loads"
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Load already exists"
                    }
                }
            },
            "get": {
                "tags": [
                    "Loads"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "list all loads",
                "description": "List all loads",
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "weight": {
                                                "type": "number"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/loads/import": {
            "post": {
                "tags": [
                    "Loads"
                ],
                "summary": "create a load",
                "description": "Create a new load",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/definitions/ImportLoads"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/companies": {
            "post": {
                "tags": [
                    "Companies"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "create a company",
                "description": "Create a new company",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Companies"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Company already exists"
                    }
                }
            },
            "get": {
                "tags": [
                    "Companies"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "List all companies",
                "description": "List all companies",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "certification": {
                                                "type": "number"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/companies/loads/{id}": {
            "post": {
                "tags": [
                    "Companies"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "create a company",
                "description": "Create a new company",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "items": {
                                "type": "string"
                            }
                        },
                        "description": "ID the company"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/AddLoadsToCompany"
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "409": {
                        "description": "Company already exists"
                    }
                }
            }
        },
        "/companies/import": {
            "post": {
                "tags": [
                    "Companies"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "create a company",
                "description": "Create a new company",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/definitions/ImportCompanies"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/session": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "authentication a user",
                "description": "Authentication a user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/AuthenticatorUser"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Driver already exists"
                    }
                }
            }
        },
        "/freights/{originCompany}": {
            "post": {
                "tags": [
                    "Freight"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "create a freight",
                "description": "Create a new Freight",
                "parameters": [
                    {
                        "name": "originCompany",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "items": {
                                "type": "string"
                            }
                        },
                        "description": "ID the origin company"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/CreateFreight"
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Driver already exists"
                    }
                }
            }
        },
        "/freights": {
            "get": {
                "tags": [
                    "Freight"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "list all freight",
                "description": "List all Freight",
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ResponseFreight"
                        }
                    },
                    "500": {
                        "description": "Driver already exists"
                    }
                }
            }
        }
    },
    "definitions": {
        "ImportLoads": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string",
                    "format": "binary"
                }
            }
        },
        "Loads": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            },
            "example": {
                "name": "load name sample",
                "weight": "load weight sample"
            }
        },
        "ImportCompanies": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string",
                    "format": "binary"
                }
            }
        },
        "Companies": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "certification": {
                    "type": "boolean"
                }
            },
            "example": {
                "name": "company name sample",
                "certification": true
            }
        },
        "AddLoadsToCompany": {
            "type": "object",
            "properties": {
                "loadsId": {
                    "type": "array"
                }
            },
            "example": {
                "loadsId": [
                    "id load onde",
                    "id load two"
                ]
            }
        },
        "CreateFreight": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "load": {
                    "type": "string"
                },
                "destinationCompany": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        }
                    }
                }
            },
            "example": {
                "price": 1500,
                "load": "c48aec95-15fc-4841-9b52-5c39d59af374",
                "destinationCompany": {
                    "id": "18d7062d-62c8-4c05-8040-8f52a2b7bd5a"
                }
            }
        },
        "ResponseFreight": {
            "type": "array",
            "properties": {
                "id": {
                    "type": "string"
                },
                "satatus": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "driver": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "driverLicense": {
                            "type": "string"
                        },
                        "createdAt": {
                            "type": "string"
                        }
                    }
                }
            },
            "example": {
                "price": "27000",
                "load": "c48aec95-15fc-4841-9b52-5c39d59af374",
                "password": "123",
                "destinationCompany": {
                    "id": "18d7062d-62c8-4c05-8040-8f52a2b7bd5a"
                }
            }
        },
        "CreateUser": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "driverLicense": {
                    "type": "string"
                }
            },
            "example": {
                "name": "user name sample",
                "email": "teste@teste.com",
                "password": "123",
                "driverLicense": "user driver license name sample"
            }
        },
        "AuthenticatorUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "example": {
                "email": "teste@teste.com",
                "password": "123"
            }
        }
    }
}